# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tableview' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod "RxSwift"
pod "RxCocoa"

  # Pods for Tableview

  target 'TableviewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TableviewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
