# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Login' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'RxSwift', '~> 3.5.0'
  pod 'RxCocoa', '~> 3.5.0'
  # Pods for Login

  target 'LoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
